parameters:
#    cygnus_sites_sdce.example.class: Cygnus\Sites\SDCEBundle\Example

services:
#    cygnus_sites_sdce.example:
#        class: %cygnus_sites_sdce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
